### ISSUE TITLE
运行php artisan chemex:install 报错

### ISSUE THREAD

**Issue by superabbite1** [celaraze/chemex#19]
运行安装报错了，php8.0 mysql5.7

![Snipaste_2021-10-19_14-01-23](https://user-images.githubusercontent.com/79433125/137852531-9d8d68ad-f66d-4588-bbee-4b37b4d17040.jpg)

**Comment by superabbite1** [comment]
好的，已经成功了，我刚才试了下好像只能领用电脑，没找到收回电脑的功能

**Comment by celaraze** [comment]
> 

取消分配即收回

**Comment by suais** [comment]
![无标题](https://user-images.githubusercontent.com/18173694/144197767-c1226aa1-7924-403d-bcd6-89d902fce9d3.png)
同样报错，请问是什么问题?

**Comment by celaraze** [comment]
> 

报错中提示的很明确，缺少PHP扩展。
