### ISSUE TITLE
无法支持AD？

### ISSUE THREAD

**Issue by tobywu6652** [celaraze/chemex#23]
保存LDAP配置后，点击测试连接按钮。显示：“执行错误：[object Object]”
在组织中导入LDAP用户，显示：“500 Internal Server Error”
DC使用的是389端口，对接其他系统（如：泛微OA、禅道都正常）

**Comment by celaraze** [comment]
确认 `php-ldap` 扩展已安装。

**Comment by tobywu6652** [comment]
确实是php-ldap的问题，安装后测试连接成功。虽然在组织中导入LDAP用户提示成功，但实际没有用户新增是什么问题？
