### ISSUE TITLE
v3.4.0 资产故障 页面，资产编号字段 bug

### ISSUE THREAD

**Issue by BlueNoob** [celaraze/chemex#28]
资产故障 页面，资产编号字段 bug
![bug2](https://i.imgur.com/6W5I6kr.jpeg)
![remex bug](https://i.imgur.com/bKiLyGk.png)

**Comment by BlueNoob** [comment]
![bug2](https://i.imgur.com/6W5I6kr.jpeg)

**Comment by BlueNoob** [comment]
### 目前已经定位到问题，此处应该是资产编号而非物品类型
`#chemex/app/Admin/Forms/MaintenanceRecordCreateForm.php`

![](https://i.imgur.com/FSah6vx.png)

**Comment by celaraze** [comment]
接收到，本周会处理下。

**Comment by celaraze** [comment]
3.4.2 已修复。

**Comment by BlueNoob** [comment]
> 3.4.2 已修复。

3.4.1哪去了？
