### ISSUE TITLE
v3.4.0 用户管理 bug

### ISSUE THREAD

**Issue by BlueNoob** [celaraze/chemex#29]
### v3.4.0 用户管理 bug
**用户管理，admin可以删除admin本身**

**Comment by celaraze** [comment]
这不算BUG吧，这是足够的自由度。
重新执行`php artisan chemex:install`即可。

**Comment by BlueNoob** [comment]
逻辑漏洞
> 这不算BUG吧，这是足够的自由度。
> 
> 重新执行`php artisan chemex:install`即可。

**Comment by celaraze** [comment]
下个版本修复。

**Comment by celaraze** [comment]
最新版已经修复此问题。
