### ISSUE TITLE
Docker部署的，没有在docker log上发现默认账户和密码

### ISSUE THREAD

**Issue by LeeZBug** [celaraze/chemex#37]
输入任何账户和密码都提示"该账户已停用，请联系管理员！"

重启一次容器后的log
Nothing to migrate.
数据库迁移完成！
Database seeding completed successfully.
Database seeding completed successfully.
Database seeding completed successfully.
Database seeding completed successfully.
Database seeding completed successfully.
升级完成！
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Sat Mar 26 13:00:05.377439 2022] [mpm_prefork:notice] [pid 12] AH00163: Apache/2.4.52 (Debian) PHP/8.1.3 configured -- resuming normal operations
[Sat Mar 26 13:00:05.377484 2022] [core:notice] [pid 12] AH00094: Command line: 'apache2 -D FOREGROUND'

**Comment by hzh1019** [comment]
我部署完也是这个提示，后台查数据库用户表内无数据。

**Comment by hzh1019** [comment]
> 

> 输入任何账户和密码都提示"该账户已停用，请联系管理员！"
> 
> 重启一次容器后的log Nothing to migrate. 数据库迁移完成！ Database seeding completed successfully. Database seeding completed successfully. Database seeding completed successfully. Database seeding completed successfully. Database seeding completed successfully. 升级完成！ AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message [Sat Mar 26 13:00:05.377439 2022] [mpm_prefork:notice] [pid 12] AH00163: Apache/2.4.52 (Debian) PHP/8.1.3 configured -- resuming normal operations [Sat Mar 26 13:00:05.377484 2022] [core:notice] [pid 12] AH00094: Command line: 'apache2 -D FOREGROUND'

docker部署后需要进入容器执行以下命令
`php artisan chemex:install
`

**Comment by gsygsy** [comment]
> > 
> 
> > 输入账户和密码都提示“该账户已使用，请联系管理员！”
> > 重载一次容器后的日志 没有要迁移的东西。数据库迁移完成！ 数据库播种成功完成。数据库种子设定成功完成。数据库种子设定成功完成。数据库种子设定成功完成。数据库种子设定成功完成。升级完成！ AH00558: apache2: 无法可靠地确定服务器的完全限定域名，使用172.17.0.2。全局设置“ServerName”指令以抑制此消息 AH00558：apache2：无法可靠地确定服务器的完全限定域名，使用 172.17.0.2。全局设置“ServerName”指令以禁止显示此消息 [Sat Mar 26 13:00:05.377439 2022] [mpm_prefork:notice] [pid 12] AH00163: Apache/2.4.52 (Debian) PHP/8.1.3 已配置 -- 正在恢复正常操作 [2022 年 3 月 26 日星期六 13:00:05.377484] [核心：通知] [pid 12] AH00094：命令行：'
> 
> docker部署需要容器进入执行以下命令后 `php artisan chemex:install ` 完成使用admin/admin登录

使用命令执行完成，用户名密码都为：admin；但是http://127.0.0.1:88/后台页面无法打开，提示该网页无法正常运作；容器日志依旧报上面一样的错误；请问该怎么解决呢？

**Comment by celaraze** [comment]
最新版已经修复此问题。
