### ISSUE TITLE
添加过的资产编号，删除后无法在次添加

### ISSUE THREAD

**Issue by ljq117** [celaraze/chemex#38]
![QQ图片20220409184341](https://user-images.githubusercontent.com/92358781/162568553-0ef74ae2-9f64-4042-a3a0-47cbd166d42a.png)
一条资产数据都没有的情况下，因为之前添加过资产编号9，删除了相关记录后，无法再次添加资产编号9的资产，会提示
![image](https://user-images.githubusercontent.com/92358781/162568596-03551df0-ed6d-4511-84dc-7f233afb768d.png)

**Comment by celaraze** [comment]
资产编号具有全局唯一性，即使这个资产编号被使用过后弃用了，也不会被重新启用。
