### ISSUE TITLE
资产编号自动生成

### ISSUE THREAD

**Issue by lyb890712** [celaraze/chemex#43]
资产编号，应该自动生成，如果资产一多，这个编号就难搞了

**Comment by celaraze** [comment]
我也想，但是没有很好的方案对各种场景做兼容。
所以，这个功能的计划是有的，还是等等吧。目前资产编号所对应的场景是已经预设了一大段编号出来，然后对资产贴一个标签，录入一个。

**Comment by celaraze** [comment]
本项目封存，重构版本已解决此问题，请等待重构版本发布。
