### ISSUE TITLE
手动配置版本composer报错

### ISSUE THREAD

**Issue by A-xianchu** [celaraze/chemex#44]
设置存储系统时报错
报错信息如下：
`[root@centos7kvm chemex]# php artisan chemex:install
正在优化配置！
Cached events cleared!
Compiled views cleared!
Application cache cleared!
Route cache cleared!
Configuration cache cleared!
Compiled services and packages files removed!
Caches cleared successfully!
正在设置存储系统！

   Error

  Call to undefined function Illuminate\Filesystem\symlink()

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:332
    328▕      */
    329▕     public function link($target, $link)
    330▕     {
    331▕         if (! windows_os()) {
  ➜ 332▕             return symlink($target, $link);
    333▕         }
    334▕
    335▕         $mode = $this->isDirectory($target) ? 'J' : 'H';
    336▕

      +11 vendor frames
  12  app/Console/Commands/Install.php:43
      Illuminate\Console\Command::call()

      +13 vendor frames
  26  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
[root@centos7kvm chemex]#`

**Comment by A-xianchu** [comment]
![image.png](https://inews.gtimg.com/newsapp_ls/0/14902154083/0.jiketuchuang.png)

**Comment by Fluox-Etine** [comment]
兄弟你这是如何解决的呢??
