### ISSUE TITLE
使用docker仓库直接挂载的方法安装，出现数据库中无用户账号密码信息

### ISSUE THREAD

**Issue by A-xianchu** [celaraze/chemex#45]
就是安装倒是成功了，但是人吧总是卡在一些奇奇怪怪的地方

***

[![image.png](https://inews.gtimg.com/newsapp_ls/0/14903858156/0.jiketuchuang.png)](https://inews.gtimg.com/newsapp_ls/0/14903858156/0.jiketuchuang.png)

***

我就卡在登录界面了

然后尝试查看数据库去看账号密码，发现数据库中`admin_users`表为空，只要涉及到user的表都为空，就很离奇，这导致我现在登不上去！装好了卡在登录这一步，已经试过了不是明文密码，靠！

**Comment by A-xianchu** [comment]
没啥问题了，我进了这个镜像的终端，重新跑了下`php artisan chemex:install`数据库就有了，但是出现了新的问题，所以我要建新的lssuers

**Comment by cnskis** [comment]
> > 没啥啥了，我进了这个但是出现了下面的问题，重新开始了有`php artisan chemex:install`新的问题，所以我要建新的问题
> 
> 怎么部署的？方便教我下么，，看了laravel官方文档，部署不出来，，，方便的话教我下，，，

进入容器，执行`php artisan chemex:install`就好了
