### ISSUE TITLE
➜ 131▕         exec('stty 2>&1', $output, $exitcode);

### ISSUE THREAD

**Issue by v587xpt** [celaraze/chemex#62]
我使用docker部署的，docker run运行成功了，但是在容器中初始化时遇到了报错：
`
[root@120 chemex_docker]# docker exec -it chemex /bin/bash
nginx: unrecognized service
php8.1-fpm: unrecognized service
cron: unrecognized service
root@c7ab548bbde5:/var/www/html/laravel# ls
Dockerfile  artisan	   config		 docs	       public	   storage
LICENSE     bootstrap	   database		 logo.png      resources   tests
README.md   composer.json  docker-compose.yml	 package.json  routes	   vendor
app	    composer.lock  docker-entrypoint.sh  phpunit.xml   server.php  webpack.mix.js
root@c7ab548bbde5:/var/www/html/laravel# cd /var/www/html/laravel && php artisan chemex:install

   ErrorException 

  exec(): Unable to fork [stty 2>&1]

  at vendor/symfony/console/Terminal.php:131
    127▕         if (!\function_exists('exec')) {
    128▕             return false;
    129▕         }
    130▕ 
  ➜ 131▕         exec('stty 2>&1', $output, $exitcode);
    132▕ 
    133▕         return self::$stty = 0 === $exitcode;
    134▕     }
    135▕ 

      +5 vendor frames 

  6   artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

`
不知道该如何解决这个问题，请求帮助；
这是我的系统相关版本：
`
[root@120 chemex_docker]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@120 chemex_docker]# uname -a
Linux 120.centos.hipro 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@120 chemex_docker]# docker -v
Docker version 18.06.3-ce, build d7080c1
`

**Comment by celaraze** [comment]
看日志的话，可能存在的原因是禁用了PHP的`exec`函数，但是镜像我都是统一封装的，如果自行没修改过PHP配置那就不太可能是这个原因。

还有一种可能是容器的权限问题，可以尝试在`docker run`的时候加入参数 `–privileged`。

**Comment by celaraze** [comment]
这个 issue 我先关闭了。
