### ISSUE TITLE
 cd /var/www/html/laravel && php artisan chemex:instal

### ISSUE THREAD

**Issue by TTTsuperpyer** [celaraze/chemex#63]
正在优化配置！
   INFO  Clearing cached bootstrap files.  

  events ............................................................................................. 1ms DONE
  views .............................................................................................. 1ms DONE
  cache .............................................................................................. 1ms DONE
  route .............................................................................................. 0ms DONE
  config ............................................................................................. 0ms DONE
  compiled ........................................................................................... 1ms DONE

正在设置存储系统！
   INFO  The [public/storage] link has been connected to [storage/app/public].  

正在配置APP密钥！

   ErrorException 

  file_get_contents(): Read of 8192 bytes failed with errno=21 Is a directory

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/KeyGenerateCommand.php:100
     96▕     {
     97▕         $replaced = preg_replace(
     98▕             $this->keyReplacementPattern(),
     99▕             'APP_KEY='.$key,
  ➜ 100▕             $input = file_get_contents($this->laravel->environmentFilePath())
    101▕         );
    102▕ 
    103▕         if ($replaced === $input || $replaced === null) {
    104▕             $this->error('Unable to set application key. No APP_KEY variable was found in the .env file.');

      +13 vendor frames 

  14  app/Console/Commands/Install.php:45
      Illuminate\Console\Command::call()
      +12 vendor frames 

  27  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by celaraze** [comment]
所以你的 `.env` 文件创建了吗？

**Comment by TTTsuperpyer** [comment]
![image](https://github.com/celaraze/chemex/assets/63111979/35ae7788-054e-47ca-be7b-d429e48afb7f)
您好，在docker上部署，在/root/InvenTree 下有个 docker.dev.env 文件，然后安装的数据库，配置如下
![image](https://github.com/celaraze/chemex/assets/63111979/d4982f88-8f3f-4574-9729-1daa4d2b8e81)，docker run -itd --name chemex --restart=always -p 8000:8000 -v /root/InvenTree/docker.dev.env:/var/www/html/laravel/docker.dev.env celaraze/chemex:latest后进入docker exec -it chemex /bin/bash，运行cd /var/www/html/laravel && php artisan chemex:install

**Comment by Gao-yu-1214** [comment]
解决了吗，我也是同样的问题
