### ISSUE TITLE
较低版本的Docker会导致服务无法启动

### ISSUE THREAD

**Issue by jiafengwang** [celaraze/chemex#65]
（一）因生产环境使用的Docker CE环境版本较低，具体docker version为以下：
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:34 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

（二）拉取2023.5.24的Latest镜像（应该是3.7.1版本chemex）部署后，查看容器log会报以下错误：
nginx: unrecognized service
php8.1-fpm: unrecognized service
cron: unrecognized service

（三）排查原因如下：
1、用当前docker拉取此前网友备份下来的3.5.2版本的chemex镜像部署容器，可正常启动使用。
2、用另一机子全新安装Debian宿主系统并安装最新版本Docker CE 24.0.2后拉取2023.5.24的Latest镜像（应该是3.7.1版本chemex）部署容器，也可正常启动使用不报错。

**Comment by celaraze** [comment]
可能会存在类似问题，新版的镜像以ubuntu22.04为基础制作。这类发行版可能会对容器环境有所要求，但考量到精力有限，chemex的版本策略是紧跟流行。
