### ISSUE TITLE
已分配归属用户的手机，借出再归还后 是无分配状态

### ISSUE THREAD

**Issue by gradient30** [celaraze/chemex#66]
如题，借出归还后：建议应该 默认回到 借出前的用户（已分配归属的人）

**Comment by celaraze** [comment]
常理来说，已分配使用者的设备不允许借出，只允许该使用者使用。借出是表现在从库存中临时借出设备给某个使用者，到期后归还设备并擦除使用数据以保证信息安全。

**Comment by gradient30** [comment]
> 常理来说，已分配使用者的设备不允许借出，只允许该使用者使用。借出是表现在从库存中临时借出设备给某个使用者，到期后归还设备并擦除使用数据以保证信息安全。

嗯，我表达不准确。其实是想说，设备是分组管理的（每个小组或部门下有一个统一的协调人员来管理一批 设备太多了），这些管理者即是负责日常调配设备使用。目前加了个自定义的 字段 能满足此需求哈

**Comment by celaraze** [comment]
我是选定一套合理的流程作为标准执行，如果有特殊需求可以自己添加字段解决。这个issue我先关闭，有其它问题再打开吧。
