### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory (Connection: mysql, SQL: select * from information_schema.tables where table_schema = chemex and table_name = migrations and table_type = 'BASE TABLE')

### ISSUE THREAD

**Issue by zxwmol** [celaraze/chemex#67]
![image](https://github.com/celaraze/chemex/assets/38974244/56199b7f-eabd-449d-90ec-5113c03a453e)

**Comment by zxwmol** [comment]
centos8+mariadb 10.5 使用管理员或者新建用户和库都报以上错误。

**Comment by celaraze** [comment]
确认你的mysql.sock是否正常，这个是数据库问题。

**Comment by celaraze** [comment]
这个issue我先关闭了，有问题再重新打开。

**Comment by yeazzzz** [comment]
[root@localhost ~]# mysql --version
mysql  Ver 14.14 Distrib 5.7.43, for Linux (x86_64) using  EditLine wrapper
[root@localhost ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

docker安装
也是遇到一样的问题
