### ISSUE TITLE
【Bug】使用exel批量导入的设备，在首次分配用户时（需要连续操作 分配两次才会成功）

### ISSUE THREAD

**Issue by gradient30** [celaraze/chemex#68]
如题：批量导入了400来台设备，
操作分配用户，第一次分配 会提示成功（实际还是分配前的用户），需要再分配一次才会成功 更新
在Mac机上使用docker一键部署的

![a1](https://github.com/celaraze/chemex/assets/39947529/26fa1a3e-8dd6-4dab-bacf-9a6ee6ef8191)

**Comment by celaraze** [comment]
我关注下这个问题。

**Comment by celaraze** [comment]
本项目封存，重构版本已解决此问题，请等待重构版本发布。
