### ISSUE TITLE
composer install 安装一直提示版本不对应

### ISSUE THREAD

**Issue by gyp719** [celaraze/chemex#70]
<img width="1476" alt="image" src="https://github.com/celaraze/chemex/assets/30563368/7cd83264-6ac9-4e1e-b490-24b537995229">

忽略版本安装 也不行
composer install --ignore-platform-reqs

**Comment by celaraze** [comment]
尝试删除程序目录下`vendor`文件夹全部内容，以及删除`composer.lock`再执行安装。
