### ISSUE TITLE
docker镜像拉取超时

### ISSUE THREAD

**Issue by lifa1225** [celaraze/chemex#71]
![image](https://github.com/celaraze/chemex/assets/59470742/9ed95383-9f6c-4002-b411-c92f90248b72)

换了几个测试环境也是超时：error pulling image configuration: download failed after attempts=6: dial tcp 104.18.125.25:443: i/o timeout
换了docker镜像源也是超时

**Comment by celaraze** [comment]
这也要提issue？考虑下本地网络环境，跟项目本身没关系。

**Comment by lifa1225** [comment]
猜测你们上传的镜像有问题已经被屏蔽了

**Comment by celaraze** [comment]
无法理解，为什么这种问题都要来项目里提issue，自己排查排查网络问题，这么多人用docker，本身hub站点在墙外，大家都正常拉取。可能dockerhub只对你屏蔽吧。
