### ISSUE TITLE
快速搜索中，中文搜索报错，SQL语句中没有引号

### ISSUE THREAD

**Issue by isle24** [celaraze/chemex#72]
快速搜索中，中文搜索报错，SQL语句中没有引号。

SQL如：

`SELECT
  count(*) AS aggregate
FROM
  `device_records`
WHERE
  (
    `id` LIKE % 手机 %
    OR `asset_number` LIKE % 手机 %
    OR `description` LIKE % 手机 %
    OR (
      EXISTS (
        SELECT
          *
        FROM
          `device_categories`
        WHERE
          `device_records`.`category_id` = `device_categories`.`id`
          AND `device_categories`.`name` LIKE % 手机 %
          AND `device_categories`.`deleted_at` IS NULL
      )
    )
    OR (
      EXISTS (
        SELECT
          *
        FROM
          `vendor_records`
        WHERE
          `device_records`.`vendor_id` = `vendor_records`.`id`
          AND `vendor_records`.`name` LIKE % 手机 %
          AND `vendor_records`.`deleted_at` IS NULL
      )
    )
    OR `name` LIKE % 手机 %
    OR `mac` LIKE % 手机 %
    OR `ip` LIKE % 手机 %
    OR `price` LIKE % 手机 %
    OR `purchased` LIKE % 手机 %
    OR `expired` LIKE % 手机 %
    OR (
      EXISTS (
        SELECT
          *
        FROM
          `admin_users`
          INNER JOIN `device_tracks` ON `device_tracks`.`user_id` = `admin_users`.`id`
        WHERE
          `device_records`.`id` = `device_tracks`.`device_id`
          AND `admin_users`.`name` LIKE % 手机 %
          AND `admin_users`.`deleted_at` IS NULL
          AND `device_tracks`.`deleted_at` IS NULL
      )
    )
    OR (
      EXISTS (
        SELECT
          *
        FROM
          `admin_users`
          INNER JOIN `device_tracks` ON `device_tracks`.`user_id` = `admin_users`.`id`
        WHERE
          `device_records`.`id` = `device_tracks`.`device_id`
          AND EXISTS (
            SELECT
              *
            FROM
              `departments`
            WHERE
              `admin_users`.`department_id` = `departments`.`id`
              AND `departments`.`name` LIKE % 手机 %
              AND `departments`.`deleted_at` IS NULL
          )
          AND `admin_users`.`deleted_at` IS NULL
          AND `device_tracks`.`deleted_at` IS NULL
      )
    )
  )
  AND `device_records`.`deleted_at` IS NULL`

**Comment by miihhaa** [comment]
修改 app/Admin/Controllers/DeviceRecordController.php
            /**
             * 快速搜索.
             */
            $grid->quickSearch(
                array_merge([
                    'asset_number',
                    'description',
                    'category.name',
                    'vendor.name',
                    'name',
                    'admin_user.name',
                    'admin_user.department.name',

去掉一些NULL的字段

**Comment by isle24** [comment]
谢谢，我试试。&nbsp;


风中之岛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月30日(星期五) 晚上8:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [celaraze/chemex] 快速搜索中，中文搜索报错，SQL语句中没有引号 (Issue #72)





 
修改 app/Admin/Controllers/DeviceRecordController.php
 /**
 * 快速搜索.
 */
 $grid-&gt;quickSearch(
 array_merge([
 'asset_number',
 'description',
 'category.name',
 'vendor.name',
 'name',
 'admin_user.name',
 'admin_user.department.name',
 
去掉一些NULL的字段

**Comment by celaraze** [comment]
关注下这个问题，后续修复。

**Comment by celaraze** [comment]
测试了下，我没遇到快速搜索这个问题，具体可以说说背景吗？

**Comment by isle24** [comment]
在设备 - 导入设备 旁边的搜索框，输入中文，回车搜索后，就会报错。查看SQL语句就是没有引号。

操作系统：CentOS 7.9.2009 x86_64
PHP版本：8.1
mysql：本地5.6/云数据库5.7 均报上述错
使用了SSL
web服务器：Nginx 1.6.1

**Comment by isle24** [comment]
如图 ： https://guyewm.oss-cn-beijing.aliyuncs.com/20230703105914.png

**Comment by celaraze** [comment]
我试了一下，确实没找到错误，唯一有区别的是我使用的是MySQL8，再确认一下是否有增加自定义的字段。

**Comment by isle24** [comment]
编码必须为 utf8mb4

**Comment by celaraze** [comment]
OK，破案了，我在文档中标注下，感谢。
