### ISSUE TITLE
同步LDAP信息

### ISSUE THREAD

**Issue by mayichuan2010** [celaraze/chemex#74]
最新的3.7.1同步LDAP信息到组织中，disable的账号也会被一同同步进来，且状态显示为账户正常，能否同步的时候跳过disable的账户，或者状态显示为账户冻结

**Comment by celaraze** [comment]
同步确实没考虑过这个问题，mark以下，后续做修复。

**Comment by celaraze** [comment]
本项目封存，重构版本已解决此问题，请等待重构版本发布。
