### ISSUE TITLE
无法插入图片 和 反向代理的设置

### ISSUE THREAD

**Issue by wintedltd** [celaraze/chemex#75]
我的Chemex部署在群晖的Docker中的，感觉非常实用！
这两天试用下来发现两个问题：

1. 编辑设备和配件里插入图片的功能用不了 一直显示上传失败 请重试
请问这个插入图片的功能是不是不能用？还是需要特殊设置？

2. 在群晖里设置反向代理之后一直出现：“此表单不安全 系统已关闭自动填充功能的提示”
登陆有出现以下提示：
 {"status":true,"data":{"message":"\u767b\u5f55\u6210\u529f !","type":"success","then":{"action":"location","value":"http:\/\/********:8099"}}}

请各位大佬帮忙看看是什么问题 谢谢！

**Comment by celaraze** [comment]
1，图片有可能是和docker中file system的权限有关，可以尝试给目录755权限，或者用高权限模式运行容器。

2，没遇到过这个问题，但是看起来和CSRF相关的错误，可能的话可以尝试去掉反代看看是否有错误提示。

**Comment by wintedltd** [comment]
非常感谢作者的回复！

1. 图片的问题我试过使用高权限模式运行，问题依旧。还有您说的给目录755权限，我也试过，好像也是不行。
    我改权限的目录是 /volume1/docker/chemex 不知道改这个对不对，如果不对的话，请指正，谢谢。
2. 关于反代的问题，我突然记起来当时安装的时候这个参数没有设置为ture
    ### 第二步：配置HTTPS
    ### 如果您使用HTTPS协议，请将下面参数修改为true
    ADMIN_HTTPS=false
    如果是这个问题导致的话，是不是直接重装就好？

**Comment by celaraze** [comment]
`ADMIN_HTTPS` 直接在 `.env` 文件中修改即可，当然如果你反代后启用了 HTTPS。
图片问题，目录应该是public/storage，这里是存放所有上传和保存的文件位置，需要有写入和修改权限。
