### ISSUE TITLE
安装提示no key

### ISSUE THREAD

**Issue by aliuzzz** [celaraze/chemex#77]
![image](https://github.com/celaraze/chemex/assets/43594093/b16562a4-96ad-4e42-8157-12208c5c45a6)

尝试执行php artisan key:generate，还是报
![image](https://github.com/celaraze/chemex/assets/43594093/18d37427-4890-455e-acf7-aae7291efdf8)

**Comment by celaraze** [comment]
根据报错请自行通过搜索引擎查下问题。显而易见，你的.env是个目录文件。
