### ISSUE TITLE
应该如何导入xlsx或者csv？使用导出的表格来导入也报错

### ISSUE THREAD

**Issue by aliuzzz** [celaraze/chemex#78]
![image](https://github.com/celaraze/chemex/assets/43594093/f273ffd7-55c6-402a-a706-fd69f4974a03)
下载下来导出的表格，然后修改了一个名称再导入回去就提示这个

**Comment by aliuzzz** [comment]
![image](https://github.com/celaraze/chemex/assets/43594093/247dff16-b80f-40ff-960e-ca1f5e1189fc)
提示了500

**Comment by celaraze** [comment]
我认为是目录权限问题，storage目录。根据部署手册给下权限。

**Comment by aliuzzz** [comment]
ok，感谢，我解决了问题，我的启动方法里laravel所属组是root，改为www-data即可恢复正常

**Comment by tizh** [comment]
能否给出具体的操作方法呢？
