### ISSUE TITLE
已安装并启用zip扩展，但报错Class “ZipArchive” not found

### ISSUE THREAD

**Issue by SeptLU** [celaraze/chemex#79]
在使用导出设备和导出设备履历的功能时会报上述错误，已经安装并且开启了zip扩展，请问有没有人有相同的问题，是如何解决的呢？

**Comment by celaraze** [comment]
这个错误就是php-zip扩展没装好。

**Comment by SeptLU** [comment]
https://flareapp.io/share/bP9pdALm#debug
具体的报错信息我分享在这个网页上，请问是否有遇到相同问题的朋友，或者劳烦作者排查一下是代码问题还是部署问题，谢谢！

**Comment by celaraze** [comment]
好的，刚看到回复不好意思，最近有点忙。
这个问题的起因是设备分配给用户 A 后，删除了用户 A 的数据，但是在设备中这个归属就产生了一个幽灵关联。我会再下个版本中优化这个问题。

目前的临时解决办法是数据库中 device_tracks 表，删除这个设备和用户的关联行记录即可。

**Comment by celaraze** [comment]
本项目封存，重构版本已解决此问题，请等待重构版本发布。
