### ISSUE TITLE
php artisan chemex:install失败有报错如图

### ISSUE THREAD

**Issue by MysTer1ous** [celaraze/chemex#80]
docker部署，已在本地mysql创建号chemex数据库，进入容器的/var/www/html/laravel目录后运行php artisan chemex:install有如下报错：
![image](https://github.com/celaraze/chemex/assets/28255159/fc4d41f7-dd74-4d24-a356-873205e4e5fb)

**Comment by yuterigele** [comment]
.envl里数据库用远程链接就可以了

**Comment by nlsp60** [comment]
> > .envl里数据库用远程链接就可以了
> 
> 请问能细说么?我.env文件已经改了： ![image](https://user-images.githubusercontent.com/28255159/257740781-75142901-ea69-43c0-9bd2-5f7539c7d15c.png)

DB_HOST 设置有问题，不应该是127.0.0.1

**Comment by liuxinglan13** [comment]
我也遇到这个问题了。。。。。。。。。。。

**Comment by MysTer1ous** [comment]
> > > .envl里数据库用远程链接就可以了
> > 
> > 
> > 请问能细说么?我.env文件已经改了： ![image](https://user-images.githubusercontent.com/28255159/257740781-75142901-ea69-43c0-9bd2-5f7539c7d15c.png)
> 
> DB_HOST 设置有问题，不应该是127.0.0.1

指向本地主机的ip不行么，请问应该怎么写

**Comment by xucaibao1979** [comment]
> > > > .envl里数据库用远程链接就可以了
> > > 
> > > 
> > > 请问能细说么?我.env文件已经改了： ![image](https://user-images.githubusercontent.com/28255159/257740781-75142901-ea69-43c0-9bd2-5f7539c7d15c.png)
> > 
> > 
> > DB_HOST 设置有问题，不应该是127.0.0.1
> 
> 指向本地主机的ip不行么，请问应该怎么写

127.0.0.1都写你本机ip就好了

**Comment by yuterigele** [comment]
就换成你服务器ip地址啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月6日(周日) 中午11:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [celaraze/chemex] php artisan chemex:install失败有报错如图 (Issue #80)




     
.envl里数据库用远程链接就可以了
  
请问能细说么?我.env文件已经改了： 
  
DB_HOST 设置有问题，不应该是127.0.0.1
  
指向本地主机的ip不行么，请问应该怎么写
  
127.0.0.1都写你本机ip就好了

**Comment by plzthxup** [comment]
之前用docker一直不成功
一直不成功，改成远程IP也是不成功的  不知道问题在哪
后台用BT面板试了下 放开端口 设置所有人访问  成功了 也是本地地址
DB_HOST=127.0.0.1
