### ISSUE TITLE
新版版安装，导入表格和上传图片都失败，

### ISSUE THREAD

**Issue by xucaibao1979** [celaraze/chemex#82]
![image](https://github.com/celaraze/chemex/assets/22347559/d7af3258-f91f-42b9-84a2-839d9a67fa24)
![image](https://github.com/celaraze/chemex/assets/22347559/3cec061d-9baa-45c6-8755-3a989f586979)

当前版本为3.7.1
导出都是好的，就导入表格和图片都提示上传失败，请重试

**Comment by tizh** [comment]
have the same problem

**Comment by celaraze** [comment]
检查下 storage 目录权限，一般给 777 或者 755 + owner 权限。

**Comment by xucaibao1979** [comment]
> 

![image](https://github.com/celaraze/chemex/assets/22347559/807ec112-cafc-4976-9105-eed387763ede)
你好，该目录已经是777权限了，还是这个问题

**Comment by xucaibao1979** [comment]
> 看导入日志，菜单左侧，日志-导入日志。

导入日志里面是空白的，暂无数据

**Comment by CaoZheng123** [comment]
@xucaibao1979 @tizh 
我也出现过类似的情况，但是通过查看日志记录我成功解决了这个问题。
具体步骤如下：
sudo docker exec -it chemex /bin/bash
cd /var/www/html/laravel/storage/logs
more laravel.log

然后我看到了这样子一条报错记录：
local.ERROR: Unable to create a directory at /var/www/html/laravel/public/uploads. {"exception":"[object] (League\\Flysystem
\\UnableToCreateDirectory(code: 0): Unable to create a directory at /var/www/html/laravel/public/uploads. at /var/www/html/laravel/vendor/league/f
lysystem/src/UnableToCreateDirectory.php:18)
[stacktrace]

然后进入 /var/www/html/laravel/public/ 看下，我发现没有uploads这个文件夹。所以就是权限的问题
只需要：
cd /var/www/html/laravel/public/
mkdir uploads
chmod 777 uploads
然后就可以上传了

**Comment by xucaibao1979** [comment]
> @xucaibao1979 @tizh 我也出现过类似的情况，但是通过查看日志记录我成功解决了这个问题。 具体步骤如下： sudo docker exec -it chemex /bin/bash cd /var/www/html/laravel/storage/logs more laravel.log
> 
> 然后我看到了这样子一条报错记录： local.ERROR: Unable to create a directory at /var/www/html/laravel/public/uploads. {"exception":"[object] (League\Flysystem \UnableToCreateDirectory(code: 0): Unable to create a directory at /var/www/html/laravel/public/uploads. at /var/www/html/laravel/vendor/league/f lysystem/src/UnableToCreateDirectory.php:18) [stacktrace]
> 
> 然后进入 /var/www/html/laravel/public/ 看下，我发现没有uploads这个文件夹。所以就是权限的问题 只需要： cd /var/www/html/laravel/public/ mkdir uploads chmod 777 uploads 然后就可以上传了

感谢您，问题解决了

**Comment by celaraze** [comment]
问题解决后这个issue我会关闭，有问题后续再开放。

**Comment by xucaibao1979** [comment]
你的镜像包里面这个文件需要提加一下文件夹uploads和755的权限，希望修复打包。

**Comment by celaraze** [comment]
> 你的镜像包里面这个文件需要提加一下文件夹uploads和755的权限，希望修复打包。

好的
