### ISSUE TITLE
功能新增

### ISSUE THREAD

**Issue by xucaibao1979** [celaraze/chemex#85]
1.资产-设备-分类里的内容并未存放数据库
  补充信息--厂商信息内容并未存放数据库
（信息内容存放数据库更便于迁移和恢复）

2.相关设备信息内容希望有导出导入功能

3.相关设备希望多选后可以删除

4.设备字段希望可以自定义（增删改）

如上为使用感受，希望楼主在百忙之中有空可以看看。谢谢。

**Comment by celaraze** [comment]
问题 1 和 2 是什么问题，每个数据都在数据库，我没听懂。
问题 3 设备批量删除是敏感操作，暂不支持。目前来说，有此需求的正确流程操作方式：向 IT 获取数据库授权，数据库批量操作删除。后续版本已经在开发中，新版会支持设备批量报废。
问题 4 现在就能自定义。

**Comment by xucaibao1979** [comment]
> 问题 1 和 2 是什么问题，每个数据都在数据库，我没听懂。 问题 3 设备批量删除是敏感操作，暂不支持。目前来说，有此需求的正确流程操作方式：向 IT 获取数据库授权，数据库批量操作删除。后续版本已经在开发中，新版会支持设备批量报废。 问题 4 现在就能自定义。

问题1.在备份的数据导入新的系统时，发现设备分类的数据和厂商的数据并未有同步过来（备份的时候我用的是root身份，不知道跟这个有没有关系）

问题2.在相关数据较多的情况下，新手可以通过导出导入的方法简单备份与恢复。小小的建议

问题4.字段可以新增加新的定义，默认老的字段无法删除，如果同样可以支持自定义的话使用起来更方便，不需要的字段可以自定义删除或者修改。 谢谢

**Comment by celaraze** [comment]
本项目封存，重构版本已解决此问题，请等待重构版本发布。
