### ISSUE TITLE
资产批量更新功能

### ISSUE THREAD

**Issue by stylewy** [celaraze/chemex#87]
你好，请问3.9.0版本，资产有批量更新功能么？
测试了下，发现通过excel导入无法实现批量更新，只能一台一台的手动修改。

**Comment by celaraze** [comment]
暂时不支持。下一个版本会有。

**Comment by dadaoggg** [comment]
> 暂时不支持。下一个版本会有。

下个版本大概会在什么时候，这个功能有点。，，，

**Comment by celaraze** [comment]
> > 暂时不支持。下一个版本会有。
> 
> 下个版本大概会在什么时候，这个功能有点。，，，

该项目只有我一个人在开发，同时这也是一个开源项目，这并不是我的工作，我会根据我的日常生活安排来编写代码。所以下一个版本何时发布我也不得而知，请体谅。

另外，批量更新是个敏感操作，着急使用自己数据库 update 。
