### ISSUE TITLE
新部署404 问题

### ISSUE THREAD

**Issue by vicecity1984** [celaraze/chemex#89]
刚刚部署出现404 请问应该排查哪里呢？
![image](https://github.com/celaraze/chemex/assets/71819705/88e9a7ba-da61-4cdb-a10b-8701396c3c0b)

![image](https://github.com/celaraze/chemex/assets/71819705/b562351f-f868-4f5e-b054-6886ad734bb8)

![image](https://github.com/celaraze/chemex/assets/71819705/90600bce-4427-47b1-b93c-fa92e6d9f933)

**Comment by celaraze** [comment]
搜索引擎搜索：laravel apache 伪静态
