### ISSUE TITLE
缺少vendor目录?

### ISSUE THREAD

**Issue by cate1019** [celaraze/chemex#92]
php artisan chemex:install，直接就报错了，缺少文件chemex/vendor/autoload.php，谁那边有vendor目录？

**Comment by celaraze** [comment]
https://github.com/celaraze/chemex/blob/main/docs/%E5%AE%89%E8%A3%85.md

**Comment by cate1019** [comment]
> https://github.com/celaraze/chemex/blob/main/docs/%E5%AE%89%E8%A3%85.md

从1-12都装过了，问题出在哪里呢？如果校验每步的正确性？

**Comment by cate1019** [comment]
更换源解决问题
`composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/`
