### ISSUE TITLE
设备菜单栏在字段中插入user字段就会报错

### ISSUE THREAD

**Issue by 1447262390** [celaraze/chemex#93]
我尝试在设备中的字段中，插入新字段，例如名称为user，字段别面位使用者，则报错如下
![image](https://github.com/celaraze/chemex/assets/51668733/5c7e070d-3e9d-4f11-80da-8d82fca76cbf)

**Comment by celaraze** [comment]
本项目封存，重构版本已解决此问题，请等待重构版本发布。
