### ISSUE TITLE
设备信息添加过保日期后，无法筛选闲置状态

### ISSUE THREAD

**Issue by maliang366359** [celaraze/chemex#95]
如图所示，设备添加过保日期，如果在保修期外，设备状态为“堪用”，此时，状态“堪用”也可以筛选出来。

![image](https://github.com/celaraze/chemex/assets/74123999/7773da62-7d3e-4b1b-a56e-298ed6857bc7)

如果设备状态在**保修期内**，设备状态为“闲置”，此时，

![image](https://github.com/celaraze/chemex/assets/74123999/e0d5cf3e-c85a-49f2-874c-490ac4ef49f8)

状态“闲置”则无法筛选出来。

![image](https://github.com/celaraze/chemex/assets/74123999/4cc3fa12-8c9f-43a6-81df-3a24add62b6d)

去掉“过保日期”之后，就可以正常在状态“闲置”里筛选出了了

![image](https://github.com/celaraze/chemex/assets/74123999/abb7ef08-cbec-450e-bae5-3672b1589fca)

**Comment by celaraze** [comment]
本项目封存，重构版本已解决此问题，请等待重构版本发布。
